baseurl = "http://test.arsano.ninja/"
title = "A Journey in Automating the Datacenter"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Chris Arceneaux"
googleAnalytics = "UA-6526296-12"
disqusShortname = "arsano-ninja"

[Privacy]

[Privacy.disqus]
    disable = false

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Chris Arceneaux"
    profile = "http://www.arsano.ninja/page/about/"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = ""
    description = "Focused mainly around Automation & Virtualization"
    github = "https://github.com/carceneaux"
    linkedin = "https://linkedin.com/in/chris-arceneaux-8903047/"
    twitter = "https://twitter.com/chris_arceneaux"
    email = "carceneaux@thinksis.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = true
    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3