name: Hugo Deployment
on:
  push:
    branches:
      # deploy on updates only on master
      - master

jobs:
  deploy:
    name: Hugo deployment
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Markdown lint
        uses: articulate/actions-markdownlint@v1
        with:
          config: .markdownlint.json
          files: 'content/'

      - name: Setup Hugo
        if: success()
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.95.0'
          # extended: true

      - name: Build Hugo
        if: success()
        run: hugo --minify --config=config.yml

      - name: Deploy
        if: success()
        uses: reggionick/s3-deploy@v3
        with:
          folder: public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true